### ISSUE TITLE
One-dimensional kernel implementation  

### ISSUE THREAD

**Issue by XingzuoPan123** [alan-turing-institute/mogp-emulator#155]
Hello! Would it be possible to implement the code of one-dimensional kernel (for setting priors) in mogp please?

**Comment by edaub** [comment]
Thanks for noting this @XingzuoPan123 -- I should be able to get to this soon once I finish a few other things I have been working on. Thanks for your patience!

**Comment by edaub** [comment]
@XingzuoPan123 I've merged the single correlation length kernel to the `devel` branch. Hopefully this does what you would like!
