### ISSUE TITLE
Rename variables in mogp_gpu to be consistent with the python implementation

### ISSUE THREAD

**Issue by ots22** [alan-turing-institute/mogp-emulator#162]

**Comment by nbarlowATI** [comment]
I got some way towards this today, namely (no pun intended): 
* Ninput -> D
* N -> n
* xs -> inputs
* ts -> targets
* xnew -> testing

Possibly still to do (though also possibly not necessary):
* update_theta -> fit
* dloglik_dtheta -> logpost_deriv
* invC -> invQ
* invCts -> invQt
